console.log("---------------------------------");
console.log("Pasos para cocinar una torta:");
console.log("---------------------------------");
console.log("Paso 1 --> Buscar los materiales necesarios");
console.log("Paso 2 --> agarrar la cantidad de materiales necesarios");
console.log("Paso 3 --> Buscar un recipiente donde poder vertir los materiales para mezclarlos");
console.log("Paso 4 --> vertir los materiales en el recipiente");
console.log("Paso 5 --> Buscar Herramienta para mezclar los materiales");
console.log("Paso 6 --> Mezclar los materiales");
console.log("Paso 7 --> Buscar el Molde donde vertir la mezcla");
console.log("Paso 8 --> Vertir la mezcla en el molde deseado para la forma de la torta");
console.log("Paso 9 --> Abrir el Horno");
console.log("Paso 10 --> meter en el horno el molde con la mezcla");
console.log("Paso 11 --> Encender el Horno");
console.log("Paso 12 --> Esperar el tiempo necesario");
console.log("Paso 13 --> Sacar la torta del horno");
console.log("Paso 14 --> dejar unos minutos que repose");
console.log("Paso 15 --> Cortar la torta");
console.log("Paso 16 --> Disfrutar ");
console.log("---------------------------------");
